version: 2
jobs:
  build:
    docker:
      - image: diehlpk/teaching
    steps:
      - checkout
      - run: find -name "*.cpp" -exec g++ "{}" -o "{}".exec ";"
      - run: find -name "*.cpp" -exec cppcheck --enable=warning,performance "{}" ";"
      - run: mkdir final 
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture1-slides -pdf lecture1.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture1-handout -pdf lecture1.tex
      - run: cd syllabus && latexmk -pdflatex="lualatex" -pdf syllabus.tex && cp syllabus.pdf ../final
      - run: cd timetable && latexmk -pdflatex="lualatex" -pdf timetable.tex  && cp timtable.pdf ../final
      - run: cp lecture*.pdf final
      - run: cd webpage && pandoc -s index.md --toc -c pandoc.css -o index.html
      - run: cp webpage/index.html webpage/pandoc.css final
      - store_artifacts:
          path: final
          destination: lectures
