version: 2
jobs:
  build:
    docker:
      - image: diehlpk/teaching
    steps:
      - checkout
      - run: find -name "*.cpp" -exec g++ "{}" -o "{}".exec ";"
      - run: find -name "*.cpp" -exec cppcheck --enable=warning,performance "{}" ";"
      - run: mkdir final
      - run: git submodule update --init --remote ParallelComputationMathExamples/
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture1-slides -pdf lecture1.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture1-handout -pdf lecture1.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture2-slides -pdf lecture2.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture2-handout -pdf lecture2.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture3-slides -pdf lecture3.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture3-handout -pdf lecture3.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture4-slides -pdf lecture4.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture4-handout -pdf lecture4.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture5-slides -pdf lecture5.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture5-handout -pdf lecture5.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture6-slides -pdf lecture6.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture6-handout -pdf lecture6.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture7-slides -pdf lecture7.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture7-handout -pdf lecture7.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture8-slides -pdf lecture8.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture8-handout -pdf lecture8.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture9-slides -pdf lecture9.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture9-handout -pdf lecture9.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture10-slides -pdf lecture10.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture10-handout -pdf lecture10.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture11-slides -pdf lecture11.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture11-handout -pdf lecture11.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture12-slides -pdf lecture12.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture12-handout -pdf lecture12.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture13-slides -pdf lecture13.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture13-handout -pdf lecture13.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture14-slides -pdf lecture14.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture14-handout -pdf lecture14.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture15-slides -pdf lecture15.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture15-handout -pdf lecture15.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture16-slides -pdf lecture16.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture16-handout -pdf lecture16.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture17-slides -pdf lecture17.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture17-handout -pdf lecture17.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture18-slides -pdf lecture18.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture18-handout -pdf lecture18.tex
      - run: 
          command: | 
            latexmk -pdflatex="lualatex --shell-escape %O %S" --jobname=lecture19-slides -pdf lecture19.tex
            latexmk -pdflatex="lualatex --shell-escape --synctex=1 %O '\def\classoption{12.pt,handout}\input{%S}'" --jobname=lecture19-handout -pdf lecture19.tex
      - run: cd syllabus && latexmk -pdflatex="lualatex" -pdf syllabus.tex && cp syllabus.pdf ../final
      - run: cd timetable && latexmk -pdflatex="lualatex" -pdf timetable.tex  && cp timetable.pdf ../final
      - run: cp lecture*.pdf final
      - run: cd webpage && pandoc -s index.md --toc -c pandoc.css -o index.html
      - run: cp webpage/index.html webpage/pandoc.css final
      - store_artifacts:
          path: final
          destination: lectures
